# -*- coding: utf-8 -*-
"""animationImage_v2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DMSVt4nz8qg4h89vKFdGsjsYRa8EH0aI
"""

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation

from matplotlib import animation, rc
from IPython.display import HTML

fig = plt.figure()

def f(x, y):
    return np.sin(x) + np.cos(y)

x = np.linspace(0, 2 * np.pi, 120)
y = np.linspace(0, 2 * np.pi, 100).reshape(-1, 1)

imSequence = []
for i in range(60):
    x += np.pi / 15.
    y += np.pi / 20.
    im = plt.imshow(f(x, y), animated=True)
    imSequence.append([im])

anim = animation.ArtistAnimation(fig, imSequence, interval = 50, blit = True, repeat_delay = 1000)

rc('animation', html = 'jshtml')
anim

# ani.save('dynamic_images.mp4')